import '@/assets/styles/global.css'
import StoreProvider from '@/components/StoreProvider'
import type { Metadata } from 'next'
import { Roboto } from 'next/font/google'


export const metadata: Metadata = {
   title: 'Create Next App',
   description: 'Generated by create next app',
}

export default function RootLayout({
   children,
}: Readonly<{
   children: React.ReactNode
}>) {
   return <StoreProvider>{children}</StoreProvider>
}
