logging:
  file:
    name: "logs.log"
    path: "logs"
  level:
    org.springframework.security: DEBUG

spring:
  config:
    import: optional:file:.env[.properties]

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 30MB

  datasource:
    url: "jdbc:mysql://localhost:3306/printer-manager-spring"
    username: "root"
    password: ""
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database: mysql
    hibernate:
      ddl-auto: "update"
    show-sql: true
    properties:
      hibernate:
        use_sql_comments: true

server:
  port: ${PORT:4000}

client:
  url: "http://localhost:3000"

redis:
  host: 'localhost'
  port: 6379

cloudflare:
  r2:
    endpoint: "https://1f17202d2f83ca70f9b726b87eea2608.r2.cloudflarestorage.com"
    access-key: "bcd2ce9da8953680450bd6490f782117"
    secret-key: "ce3152122387b96162b4e41ceca68246d864ee92e614442ed2e1c3ce5186f506"
    bucket-name: "pdf-storage"
    presigned-url-expire-time: 10800

jwt:
  rsa_key_size: 2048
  access_token_expire_time: 300
  refresh_token_expire_time: 86400

cloudinary:
  cloud_name: ${CLOUDINARY_CLOUD_NAME}
  api_key: ${CLOUDINARY_API_KEY}
  secret_key: ${CLOUDINARY_SECRET_KEY}