spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/printer-manager-spring"
    username: "root"
    password: ""
    driver-class-name: "com.mysql.cj.jdbc.Driver"

  jpa:
    database: "mysql"
    hibernate:
      ddl-auto: "update"
    show-sql: true

server:
  port: 4000